// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://alimhljadztnxhkjrsly.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFsaW1obGphZHp0bnhoa2pyc2x5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNzg1NzcsImV4cCI6MjA1Nzk1NDU3N30.wuW9H4PLyytKjlDCxvwS0n0H0uE1Q3y1x4tqpuhvr04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);